main:
  project_name: "my_ml_project"
  experiment_name: "random_forest_experiment"
  steps: "all"  # o "download,basic_cleaning,train_random_forest"

data_processing:
  sample: "student_entry_performance_modified.csv"
  test_size: 0.2
  val_size: 0.2
  random_state: 42
  stratify_column: "Performance"


# modeling:
#   test_size: 0.2
#   val_size: 0.2
#   random_seed: 42
#   stratify_by: "price_category"
#   max_tfidf_features: 100
  
#   random_forest:
#     n_estimators: 100
#     max_depth: 10
#     min_samples_split: 2

# data_check:
#   kl_threshold: 0.2